DELETE http://localhost:3003/api/blogs/62768cb64ea4132704c06483
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbG8xIiwiaWQiOiI2Mjc2MjM1NmE1MGUyY2Q1ZjQ1N2QzNTMiLCJpYXQiOjE2NTE5Mzg1NjcsImV4cCI6MTY1MTk0MjE2N30.PsdxBsHJGl4lqQbpU5jW3NZJzFsUZBsCgwmLegA2X_w